name: 'training spawner with single fixed hp set'

resources:
  conda_env: 'pytorch'
  wandb_project: 'espeon'
  cluster: 'baobab'

logging:
  checkpoint_dir: 'data/checkpoints'
  log_dir: 'data/logs'
  video_dir: 'data/videos'
  record: false

parameters:
  # Generic
  task: 'train'
  algo: 'ddpg-td3'
  cuda: false
  num_seeds: 5
  benchmark: 'mujoco'

  # Training
  num_timesteps: 1e7
  training_steps_per_iter: 2
  eval_steps_per_iter: 10
  eval_frequency: 5000

  # Model
  layer_norm: true

  # Optimization
  actor_lr: 2.5e-4
  critic_lr: 2.5e-4
  with_scheduler: false
  clip_norm: 40.0
  wd_scale: 0.

  # Algorithm
  rollout_len: 2
  batch_size: 64
  gamma: 0.99
  mem_size: 100000
  noise_type: '"ou_0.3"'
  pn_adapt_frequency: 50
  polyak: 0.005
  targ_up_freq: 100
  n_step_returns: true
  lookahead: 10
  ret_norm: false
  popart: false

  # TD3
  clipped_double: true
  targ_actor_smoothing: true
  td3_std: 0.2
  td3_c: 0.5
  actor_update_delay: 2

  # Prioritized replay
  prioritized_replay: false
  alpha: 0.3
  beta: 1.
  ranked: false
  unreal: false

  # Distributional RL
  use_c51: false
  use_qr: false
  c51_num_atoms: 51
  num_tau: 200
